import galileoVaultArtifact from "@/artifacts/contracts/PolicyVaultV4SwapGalileo.sol/PolicyVaultV4SwapGalileo.json";
import { isAddress, isHex, type Address, type Hex } from "viem";

export const GALILEO_CHAIN_ID = 16602;
export interface GalileoVaultStackAddresses {
  adapter: Address;
  pool: Address;
  sandboxToken: Address;
  vaultRegistry: Address;
}

export interface VerifiedGalileoVaultStack extends GalileoVaultStackAddresses {
  executor: Address;
  poolId: Hex;
  proofRegistry: Address;
}

export const GALILEO_DEFAULT_VAULT_POLICY = {
  cooldownSeconds: 15n,
  dailyCap0G: 50_000_000_000_000_000n,
  defaultMinOutBps: 9_900,
  maxDeadlineWindowSeconds: 300n,
  maxExposure0G: 50_000_000_000_000_000n,
  perTradeCap0G: 10_000_000_000_000_000n,
} as const;

/**
 * Browser-safe configuration only. There are deliberately no generic or
 * mainnet fallbacks here: an incomplete stack keeps every wallet action off.
 */
export function resolveGalileoVaultStack(): GalileoVaultStackAddresses | null {
  const values = {
    adapter: process.env.NEXT_PUBLIC_GALILEO_SANDBOX_ADAPTER_ADDRESS,
    pool: process.env.NEXT_PUBLIC_GALILEO_SANDBOX_POOL_ADDRESS,
    sandboxToken: process.env.NEXT_PUBLIC_GALILEO_SANDBOX_TOKEN_ADDRESS,
    vaultRegistry: process.env.NEXT_PUBLIC_VAULT_REGISTRY_V4_GALILEO_ADDRESS,
  };
  if (!Object.values(values).every((value) => value && isAddress(value, { strict: true }))) return null;
  return values as GalileoVaultStackAddresses;
}

/** Public creation bytecode generated by Hardhat for the Galileo-only vault. */
export const galileoVaultDeploymentBytecode = (() => {
  const bytecode = (galileoVaultArtifact as { bytecode?: unknown }).bytecode;
  if (typeof bytecode !== "string" || !isHex(bytecode) || bytecode === "0x") {
    throw new Error("PolicyVaultV4SwapGalileo bytecode is missing. Run npm run contracts:compile before building the app.");
  }
  return bytecode as Hex;
})();

export const galileoVaultDeploymentAbi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { name: "initialOwner", type: "address" },
      { name: "executor_", type: "address" },
      { name: "adapter_", type: "address" },
      { name: "proofRegistry_", type: "address" },
      {
        name: "initialPolicy",
        type: "tuple",
        components: [
          { name: "perTradeCap0G", type: "uint256" },
          { name: "dailyCap0G", type: "uint256" },
          { name: "maxExposure0G", type: "uint256" },
          { name: "cooldownSeconds", type: "uint256" },
          { name: "maxDeadlineWindowSeconds", type: "uint256" },
          { name: "defaultMinOutBps", type: "uint16" },
        ],
      },
      { name: "token", type: "address" },
      { name: "poolId", type: "bytes32" },
      { name: "registry_", type: "address" },
    ],
  },
] as const;

export const galileoVaultRegistryAbi = [
  { type: "function", name: "vaultOf", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "isAttestedVault", stateMutability: "view", inputs: [{ name: "vault", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "attestVault", stateMutability: "nonpayable", inputs: [{ name: "vault", type: "address" }], outputs: [] },
  { type: "function", name: "configureAdapter", stateMutability: "nonpayable", inputs: [{ name: "adapter_", type: "address" }], outputs: [] },
  { type: "function", name: "expectedAdapter", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "expectedProofRegistry", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "expectedToken", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "expectedPoolId", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bytes32" }] },
  { type: "function", name: "expectedExecutor", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
] as const;

export const galileoVaultAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "actionHash", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "agentKey", type: "bytes32" },
      { indexed: true, internalType: "bool", name: "isBuy", type: "bool" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountIn", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amountOut", type: "uint256" },
      { indexed: false, internalType: "bytes32", name: "auditRoot", type: "bytes32" },
    ],
    name: "TradeExecuted",
    type: "event",
  },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "executor", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "swapAdapter", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "proofRegistry", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "vaultRegistry", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "mockAdapterAllowed", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "allowedTokens", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "allowedPools", stateMutability: "view", inputs: [{ name: "", type: "bytes32" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "executorRevoked", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "agentKeyEnabled", stateMutability: "view", inputs: [{ name: "key", type: "bytes32" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "policy", stateMutability: "view", inputs: [], outputs: [{ name: "perTradeCap0G", type: "uint256" }, { name: "dailyCap0G", type: "uint256" }, { name: "maxExposure0G", type: "uint256" }, { name: "cooldownSeconds", type: "uint256" }, { name: "maxDeadlineWindowSeconds", type: "uint256" }, { name: "defaultMinOutBps", type: "uint16" }] },
  { type: "function", name: "dailySpent0G", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "dailyWindowStart", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "lastTradeAt", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "openExposure0G", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "positionUnits", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "agentPositionUnits", stateMutability: "view", inputs: [{ name: "", type: "bytes32" }, { name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "usedActionHashes", stateMutability: "view", inputs: [{ name: "", type: "bytes32" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "minOutFor", stateMutability: "view", inputs: [{ name: "", type: "address" }, { name: "", type: "address" }, { name: "quoted", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "policyHash", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bytes32" }] },
  { type: "function", name: "actionHashFor", stateMutability: "pure", inputs: [{ name: "vaultActionHash", type: "bytes32" }, { name: "auditRoot", type: "bytes32" }, { name: "policySnapshotHash", type: "bytes32" }], outputs: [{ name: "", type: "bytes32" }] },
  { type: "function", name: "vaultActionHashFor", stateMutability: "view", inputs: [{ name: "isBuy", type: "bool" }, { name: "r", type: "tuple", components: [{ name: "tokenIn", type: "address" }, { name: "tokenOut", type: "address" }, { name: "amountIn", type: "uint256" }, { name: "quotedAmountOut", type: "uint256" }, { name: "amountOutMin", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "agentKey", type: "bytes32" }, { name: "poolId", type: "bytes32" }, { name: "vaultActionHash", type: "bytes32" }, { name: "actionHash", type: "bytes32" }, { name: "policySnapshotHash", type: "bytes32" }, { name: "auditRoot", type: "bytes32" }] }], outputs: [{ name: "", type: "bytes32" }] },
  { type: "function", name: "buy", stateMutability: "nonpayable", inputs: [{ name: "r", type: "tuple", components: [{ name: "tokenIn", type: "address" }, { name: "tokenOut", type: "address" }, { name: "amountIn", type: "uint256" }, { name: "quotedAmountOut", type: "uint256" }, { name: "amountOutMin", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "agentKey", type: "bytes32" }, { name: "poolId", type: "bytes32" }, { name: "vaultActionHash", type: "bytes32" }, { name: "actionHash", type: "bytes32" }, { name: "policySnapshotHash", type: "bytes32" }, { name: "auditRoot", type: "bytes32" }] }], outputs: [{ name: "out", type: "uint256" }] },
  { type: "function", name: "sell", stateMutability: "nonpayable", inputs: [{ name: "r", type: "tuple", components: [{ name: "tokenIn", type: "address" }, { name: "tokenOut", type: "address" }, { name: "amountIn", type: "uint256" }, { name: "quotedAmountOut", type: "uint256" }, { name: "amountOutMin", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "agentKey", type: "bytes32" }, { name: "poolId", type: "bytes32" }, { name: "vaultActionHash", type: "bytes32" }, { name: "actionHash", type: "bytes32" }, { name: "policySnapshotHash", type: "bytes32" }, { name: "auditRoot", type: "bytes32" }] }], outputs: [{ name: "out", type: "uint256" }] },
  { type: "function", name: "depositNative", stateMutability: "payable", inputs: [], outputs: [] },
  { type: "function", name: "withdrawNative", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "setPaused", stateMutability: "nonpayable", inputs: [{ name: "value", type: "bool" }], outputs: [] },
  { type: "function", name: "revokeExecutor", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "setAgentKeyEnabled", stateMutability: "nonpayable", inputs: [{ name: "key", type: "bytes32" }, { name: "enabled", type: "bool" }], outputs: [] },
] as const;

export const galileoSandboxPoolAbi = [
  { type: "function", name: "adapter", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "nativeReserve", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "tokenReserve", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "quoteExactIn", stateMutability: "view", inputs: [{ name: "tokenIn", type: "address" }, { name: "amountIn", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
] as const;

export const galileoFaucetAbi = [
  { type: "function", name: "claimFaucet", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
] as const;
